name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Test on ${{ matrix.os }} for ${{ matrix.lang }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install Python 3.x dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install tox numpy pandas

    - name: Install system dependencies for R tests
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update; sudo apt-get install -y libcurl4-openssl-dev
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3' 
    
    - name: Install Metaflow R 
      run: |
        Rscript -e 'install.packages("devtools", repos="https://cloud.r-project.org", Ncpus=8)'
        Rscript -e 'devtools::install_github("Netflix/metaflow", subdir="R")'
        Rscript -e 'metaflow::install()'

    - name: Install R dependencies for R tests
      run:
        Rscript -e 'install.packages(c("data.table", "caret", "glmnet", "gbm"), repos="https://cloud.r-project.org", Ncpus=8)'    
    
    - name: Run tutorials tests
      run: cd tests; bash test.sh 

